import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';

<style>
@import url('https://fonts.googleapis.com/css2?family=Akaya+Telivigala&display=swap');
</style>

// Generated by create-react-app
ReactDOM.render(
    <App />,
  document.getElementById('root')
);